name: Update Grammar Cache

on:
  # Run weekly to keep cache fresh
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual trigger
  workflow_dispatch:
  # Run when grammars.json changes
  push:
    paths:
      - 'crates/breeze-grammars/grammars.json'
      - '.github/workflows/grammars-cache.yml'

jobs:
  build-and-cache-grammars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1

      - name: Install tree-sitter-cli
        run: |
          cargo install tree-sitter-cli

      - name: Cache precompiled grammars
        id: cache-grammars
        uses: actions/cache@v4
        with:
          path: crates/breeze-grammars/precompiled
          key: grammars-${{ hashFiles('crates/breeze-grammars/grammars.json') }}-v1
          enableCrossOsArchive: true

      - name: Build grammars for all platforms
        if: steps.cache-grammars.outputs.cache-hit != 'true'
        run: |
          ./tools/build-grammars --all-platforms
