name: Build Tree-sitter Parsers

on:
  # Run weekly to keep cache fresh
  schedule:
    - cron: '0 0 * * 0'
  # Allow manual trigger
  workflow_dispatch:
  # Run on push to main
  push:
    branches:
      - main
  # Run on pull requests
  pull_request:
    branches:
      - main

jobs:
  build-all-platforms:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: '0.14.1'

      - name: Install dependencies
        run: npm ci

      - name: Cache grammar repositories
        id: cache-grammars
        uses: actions/cache@v4
        with:
          path: grammars
          key: grammars-${{ hashFiles('grammars.json') }}-v1
          restore-keys: |
            grammars-${{ hashFiles('grammars.json') }}-
            grammars-

      - name: Fetch grammars
        if: steps.cache-grammars.outputs.cache-hit != 'true'
        run: npm run fetch

      - name: Build for all platforms
        run: npm run build:all

      - name: Create npm packages
        run: npm run create-packages

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tree-sitter-parsers-all-platforms
          path: |
            dist/
            platforms/
          retention-days: 7

  test-platforms:
    needs: build-all-platforms
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: ['20', '22']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: tree-sitter-parsers-all-platforms

      - name: Test binary
        run: |
          node -e "console.log(require('./index.js').binaryPath)"
          node bin/tree-sitter-parsers-path.js

  publish:
    needs: test-platforms
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: tree-sitter-parsers-all-platforms

      - name: Check if version changed
        id: version-check
        run: |
          PUBLISHED_VERSION=$(npm view @breeze/tree-sitter-parsers version 2>/dev/null || echo "0.0.0")
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          if [ "$PUBLISHED_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Version changed from $PUBLISHED_VERSION to $CURRENT_VERSION"
            echo "publish=true" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged at $CURRENT_VERSION"
            echo "publish=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish packages
        if: steps.version-check.outputs.publish == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run publish-all
